### ISSUE TITLE
Configuration problem

### ISSUE THREAD

**Issue by krysiekBP** [Bragi26/edd-paynow-gateway#1]
Hello
I wanted to use this plugin in my webpage.
I installed it and turned on in EDD.
Test mode is turned on.
I have test mode enabled.
After going with to the payment, the webpage refreshes without moving to the paynow page.
I would be gratefull for help
Regards.
Bartosz

**Comment by Bragi26** [comment]
Hello
Thank you for your comment. I looked into it, and you are right, there was a minor issue with my plugin. Please check the newest version and it should work now.
Regards.
Piotr
